# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=200)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocationArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.ManyToManyField(blank=True, to='heatmap.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='geoobject',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='geoobject',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heatmap.LocationArea'),
        ),
    ]
